[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ["full", "extra-traits", "fold", "visit-mut"] }
quote = { version = "*" }
proc-macro2 = { version = "*" }
# TODO
